# Generated by Django 4.1.7 on 2023-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=10)),
            ],
        ),
    ]
