# Generated by Django 4.1.7 on 2023-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaszk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='group',
            field=models.CharField(choices=[('KAC', 'KAC'), ('Gazdaságtudományi Szakkollégium', 'GTSZK'), ('Pedagódusképső Szakkollégium', 'PKSZK'), ('Műszaki Szakkollégium', 'MSZK')], max_length=50),
        ),
    ]
