# Generated by Django 4.1.7 on 2023-02-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaszk', '0002_news_img_alter_news_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
    ]
