# Generated by Django 4.1.7 on 2023-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaszk', '0003_remove_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='group',
            field=models.CharField(choices=[('KAC', 'KAC'), ('GTSZK', 'GTSZK'), ('PKSZK', 'PKSZK'), ('MSZK', 'MSZK')], max_length=50),
        ),
    ]
