# Generated by Django 4.2 on 2023-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('KAC', 'KAC'), ('GTSZK', 'GTSZK'), ('PKSZK', 'PKSZK'), ('MSZK', 'MSZK')], max_length=50)),
            ],
        ),
    ]
